import os
import asyncio
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from src.retrieval.vector_retriever import get_vectorstore
from src.ingestion.ingest import ingestNewFiles
from src.generation.ragChain import route_and_ask, get_rag_chain, ROUTER_PROMPT
from src.generation.sql_agent import query_database
from src.config import LLM_MODEL_NAME

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Define Pydantic request model
class ChatRequest(BaseModel):
    question: str

# Global application state holder for warm resources
app_state = {}

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    PRODUCTION LIFESPAN HANDLER
    This code runs ONCE when the server boots up.
    It pre-loads the embedding model, vector store, and ingests missing documents into RAM/SQLite.
    Subsequent user requests reuse these warm in-memory objects instantly!
    """
    print("\n[SERVER STARTUP] Warming up Verano RAG server...")
    
    # 1. Warm-load Vectorstore & Embedding Model into memory
    print("[SERVER STARTUP] Loading HuggingFace embeddings & Chroma vectorstore into RAM...")
    vectorstore = get_vectorstore()
    app_state["vectorstore"] = vectorstore
    
    # 2. Check for missing documents & ingest
    print("[SERVER STARTUP] Checking document ingestion status...")
    ingestNewFiles(vectorstore)
    
    print("[SERVER STARTUP] Warm-up complete! Server ready to serve instant requests.\n")
    yield
    print("[SERVER SHUTDOWN] Cleaning up server resources...")

# Create FastAPI application
app = FastAPI(
    title="Verano Apparel RAG Knowledge API",
    description="Enterprise Dual-Engine (Hybrid RAG + Text-to-SQL Agent) Backend API",
    version="1.0.0",
    lifespan=lifespan
)

# Enable CORS so any website or widget can communicate with this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
def health_check():
    """Returns backend health status."""
    return {"status": "online", "system": "Verano RAG API", "warmed": "vectorstore" in app_state}

@app.post("/api/chat")
def chat_endpoint(request: ChatRequest):
    """
    Standard synchronous JSON endpoint.
    Routes the query to Tabular SQL or Prose RAG and returns full answer.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    try:
        answer = route_and_ask(request.question)
        return {"question": request.question, "answer": answer}
    except Exception as e:
        print("[CHAT ERROR]", e)
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/chat/stream")
async def chat_stream_endpoint(question: str):
    """
    PRODUCTION STREAMING ENDPOINT (Server-Sent Events / SSE)
    Streams LLM tokens live as they are generated by Gemini.
    Provides sub-second perceived latency to the end user!
    """
    if not question.strip():
        raise HTTPException(status_code=400, detail="Question parameter is required.")

    async def token_generator():
        # First, route the query (Tabular vs Prose)
        router_llm = ChatGoogleGenerativeAI(model=LLM_MODEL_NAME, temperature=0.0)
        prompt = ChatPromptTemplate.from_template(ROUTER_PROMPT)
        route_chain = prompt | router_llm | StrOutputParser()
        
        raw_route = route_chain.invoke({"question": question})
        route = str(raw_route).strip().lower()
        
        if "tabular" in route:
            # Yield metadata signal first
            yield "data: [ROUTE: TABULAR_SQL]\n\n"
            ans = query_database(question)
            yield f"data: {ans}\n\n"
        else:
            yield "data: [ROUTE: PROSE_HYBRID_RAG]\n\n"
            rag_chain = get_rag_chain()
            # Stream tokens asynchronously from LLM
            for chunk in rag_chain.stream(question):
                # Format chunk as Server-Sent Event
                cleaned_chunk = str(chunk).replace("\n", "\\n")
                yield f"data: {cleaned_chunk}\n\n"
                await asyncio.sleep(0.01)
                
        yield "data: [DONE]\n\n"

    return StreamingResponse(token_generator(), media_type="text/event-stream")

# Mount frontend directory for static serving
FRONTEND_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "frontend")

if os.path.exists(FRONTEND_DIR):
    app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")

    @app.get("/")
    def read_root():
        widget_page = os.path.join(FRONTEND_DIR, "widget.html")
        if os.path.exists(widget_page):
            return FileResponse(widget_page)
        return {"message": "Verano RAG API Server is running. Visit /docs for OpenAPI documentation."}
